#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
decompile_driver.ghidra.py - Ghidra headless decompilation script.

Runs inside Ghidra's Jython environment via analyzeHeadless -postScript.
Exports decompiled pseudocode (.c) and a function summary (.txt) for
a Windows kernel driver (.sys).

Invoked by copy_drivers.py --decompile, not run directly:

  analyzeHeadless <proj_dir> <proj_name> \\
      -import driver.sys \\
      -postScript decompile_driver.ghidra.py <output_dir> \\
      -deleteProject

Output files (written to <output_dir>):
  <driver>_decompiled.c   — Pseudocode for all functions
  <driver>_functions.txt  — Function list with addresses and sizes
"""

# Ghidra/Jython builtins: currentProgram, getScriptArgs, monitor, etc.
# These are injected by Ghidra's script environment.

from ghidra.app.decompiler import DecompInterface  # noqa: F401
from ghidra.util.task import ConsoleTaskMonitor  # noqa: F401
import os


def get_output_dir():
    """Get output directory from script arguments, default to program dir."""
    args = getScriptArgs()  # noqa: F821 — Ghidra builtin
    if args and len(args) > 0:
        return args[0]
    info = currentProgram.getDomainFile()  # noqa: F821
    return os.path.dirname(info.getPathname()) if info else "."


def get_driver_name():
    """Get the base name of the imported binary (without extension)."""
    name = currentProgram.getName()  # noqa: F821
    if "." in name:
        name = name.rsplit(".", 1)[0]
    return name


def decompile_all(output_dir):
    driver_name = get_driver_name()
    c_path = os.path.join(output_dir, "{}_decompiled.c".format(driver_name))
    txt_path = os.path.join(output_dir, "{}_functions.txt".format(driver_name))

    decomp = DecompInterface()
    decomp.openProgram(currentProgram)  # noqa: F821

    task_monitor = ConsoleTaskMonitor()
    listing = currentProgram.getListing()  # noqa: F821
    func_iter = listing.getFunctions(True)  # True = forward iteration

    functions = []
    for func in func_iter:
        entry = func.getEntryPoint()
        name = func.getName()
        size = func.getBody().getNumAddresses()
        functions.append((entry, name, size))

    # Sort by address
    functions.sort(key=lambda f: f[0].getOffset())

    print("[ghidra] Decompiling {} functions from {} ...".format(
        len(functions), driver_name
    ))

    # Write function summary
    with open(txt_path, "w") as txt:
        txt.write("# Function list for {}\n".format(driver_name))
        txt.write("# Address          Name                                     Size\n")
        txt.write("# " + "-" * 70 + "\n")
        for entry, name, size in functions:
            txt.write("  {:<18s} {:<40s} {:>6d}\n".format(
                str(entry), name, size
            ))
        txt.write("\n# Total: {} functions\n".format(len(functions)))

    # Decompile and write pseudocode
    with open(c_path, "w") as out:
        out.write("// Decompiled pseudocode for {}\n".format(driver_name))
        out.write("// Generated by Ghidra headless analysis\n")
        out.write("// Function count: {}\n\n".format(len(functions)))

        decompiled_count = 0
        for i, (entry, name, size) in enumerate(functions):
            if i % 50 == 0:
                print("[ghidra] Progress: {}/{} functions".format(i, len(functions)))

            func = listing.getFunctionAt(entry)
            if func is None:
                continue

            result = decomp.decompileFunction(func, 60, task_monitor)
            if result and result.depiledFunction():
                code = result.getDecompiledFunction().getC()
                out.write("// ---- {} @ {} (size: {}) ----\n".format(
                    name, entry, size
                ))
                out.write(code)
                out.write("\n\n")
                decompiled_count += 1
            else:
                out.write("// ---- {} @ {} — decompilation failed ----\n\n".format(
                    name, entry
                ))

    print("[ghidra] Done. Decompiled {}/{} functions.".format(
        decompiled_count, len(functions)
    ))
    print("[ghidra] Pseudocode: {}".format(c_path))
    print("[ghidra] Functions:  {}".format(txt_path))


# Entry point — called by Ghidra's script runner
output_dir = get_output_dir()
if not os.path.isdir(output_dir):
    os.makedirs(output_dir)
decompile_all(output_dir)
